# yamllint disable rule:line-length
---
name: setup environment

description: load values from 1password vault

inputs:

  instance:
    description: input value that can be used to control which actions are run
    required: false
    default: ""

runs:
  using: "composite"

  steps:

    - name: load values from 1password vault
      uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0    # v2.0.0
      with:
        export-env: true
      env:
        DOCKER_LOGIN: op://platform/svc-dockerhub/username
        DOCKER_PASSWORD: op://platform/svc-dockerhub/password
        SNYK_TOKEN: op://platform/svc-snyk/api-token
