# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: development build and release

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:

  dev-release:
    name: development build and release
    uses: twplatformlabs/gha-tools-action/.github/workflows/job-container-dev-release.yaml@main
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    with:
      image: gha-container-infra-aws
      organization: twdps
      opencontainer-labels: true
      before-static-analysis: true
      snyk-scan: true
      snyk-severity-threshold: medium
      snyk-organization: twdps
      bats-test: true
      bats-run-container-name: gha-container-infra-aws-image
      bats-entry-point: /bin/ash
      bats-test-path: test/gha-container-infra-aws.bats
